apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaks
  labels:
    app: myaks
  namespace: namespace-workflow-1711102693845
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myaks
  template:
    metadata:
      labels:
        app: myaks
    spec:
      containers:
        - name: myaks
          image: acrworkflow1711102693845.azurecr.io/image-workflow-1711102693845:latest
          ports:
            - containerPort: 5000