apiVersion: v1
kind: Service
metadata:
  name: myaks
  namespace: namespace-workflow-1711102693845
spec:
  type: LoadBalancer
  selector:
    app: myaks
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000